import React from 'react'
import Navbar from '../Navbar'

function Confirm() {
    return (
        <>

            <Navbar />
            
            <section className="confirm-section">
                <div className="container">
                    <div className="row d-flex jc-center ai-center">
                        <div className="col">
                            <div className="card">
                                <div className="card-body p-4">
                                    <div className="row">
                                        <div className="col-lg-6">
                                            {/* <h5 className="mb-3">
                                                <a href="#!" className="text-body">
                                                    <i className="fas fa-long-arrow-alt-left me-2"></i>
                                                    Continue shopping
                                                </a>
                                            </h5> */}

                                            <div className='confirm'>
                                                <div className='estimated_work'>
                                                    <h3>Estimated scope of work: <span> 2-3 hours </span></h3>
                                                    <h6>Hourly rate $91/hr</h6>
                                                    <p>The final quote will be generated by our vetted handyman after they discuss with you.</p>
                                                </div>

                                                <div className="summary">
                                                    <h5>Appointment Summary</h5>

                                                    <div className='summary_body'>
                                                        <div className="service_detail">
                                                            <div className='d-flex jc-between ai-center'>
                                                                <div className="s_name">
                                                                    <h6>Handyman Services</h6>
                                                                </div>
                                                                <div className="s_charges">
                                                                    <p>$91.00/hr</p>
                                                                </div>
                                                            </div>
                                                            <div className='d-flex jc-between ai-center'>
                                                                <div className="s_name">
                                                                    <h6>Security & support fee</h6>
                                                                </div>
                                                                <div className="s_charges">
                                                                    <p>$14.90</p>
                                                                </div>
                                                            </div>
                                                        </div>

                                                        <div className="summary_detail">
                                                            <div className="estimated_time d-flex jc-between ai-center">
                                                                <h6>Estimated</h6>
                                                                <p>2-3 hours</p>
                                                            </div>

                                                            <div className="estimated_time d-flex jc-between ai-center">
                                                                <h6>Requested Time</h6>
                                                                <p>Sep 18 2023, 12pm - 1pm</p>
                                                            </div>

                                                        </div>

                                                    </div>

                                                    <div className="confirm_btn">
                                                        <button className='btn'>Confirm and Book</button>
                                                    </div>
                                                </div>
                                            </div>


                                        </div>

                                        <div className="col-lg-6">
                                            <div className="card cart-detail text-white" style={{ height: "100%" }}>
                                                <div className="card-body">
                                                    <div className="d-flex jc-between ai-center mb-4">
                                                        <h5 className="mb-0">User Details</h5>
                                                        <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/avatar-6.webp" className="img-fluid rounded-3" style={{ width: "45px" }} alt="Avatar" />
                                                    </div>

                                                    <form className="mt-4">
                                                        <div className="form-outline form-white mb-4">
                                                            <input type="text" className="form-control form-control-lg" placeholder="Enter Full Name" required />
                                                        </div>

                                                        <div className="form-outline form-white mb-4">
                                                            <input type="email" className="form-control form-control-lg" placeholder="Enter Email" required />
                                                        </div>

                                                        <div className="form-outline form-white mb-4">
                                                            <input type="text" className="form-control form-control-lg" placeholder="Enter Contact Number" required />
                                                        </div>

                                                        <div className="row">
                                                            <div className="col-md-6 mb-4">
                                                                <div className="form-outline form-white">
                                                                    <input type="text" className="form-control form-control-lg" placeholder="Enter City" required />
                                                                </div>
                                                            </div>
                                                            <div className="col-md-6 mb-4">
                                                                <div className="form-outline form-white">
                                                                    <input type="text" className="form-control form-control-lg" placeholder="Enter Address" required />
                                                                </div>
                                                            </div>
                                                        </div>

                                                        <hr className="my-4" />

                                                        <div className="d-flex jc-between">
                                                            <p className="mb-2">Subtotal</p>
                                                            <p className="mb-2">$4798.00</p>
                                                        </div>

                                                        <div className="d-flex jc-between">
                                                            <p className="mb-2">Shipping</p>
                                                            <p className="mb-2">$20.00</p>
                                                        </div>

                                                        <div className="d-flex jc-between mb-4">
                                                            <p className="mb-2">Total(Incl. taxes)</p>
                                                            <p className="mb-2">$4818.00</p>
                                                        </div>

                                                        <button type="submit" className="btn checkout-btn btn-block btn-lg">
                                                            <div className="d-flex jc-between">
                                                                <span>$4818.00</span>
                                                                <span>Checkout <i className="fas fa-long-arrow-alt-right ms-2"></i></span>
                                                            </div>
                                                        </button>
                                                    </form>

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div >
            </section >
        </>
    )
}

export default Confirm
